# Day 20 In-Class: Intro to Artificial Neural Networks

<img src="http://www.bogotobogo.com/python/scikit-learn/images/NeuralNetwork1/NN-with-components-w11-etc.png" width=600px>

### Agenda:

1. Review pre-class assignment
2. Work on semester projects!

----
# 1. Review pre-class assignment

Below is the solution to the pre-class assignment, we're going to talk through this to make sure we all understand what's happening.

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# input data (hours of sleep, hours of study)
X = np.array([[3,5], [5,1], [10,2]])

# normalized X
X_norm = X / np.max(X)
print("X_norm =")
print(X_norm)

# output data (test score)
y = np.array([[75], [83], [93]])

# normalized y
y_norm = y/100
print("y_norm =")
print(y_norm)

# Neural Network properties
inputLayerSize = 2
outputLayerSize = 1
hiddenLayerSize = 3

# Define synapse weights
W1 = np.random.randn(inputLayerSize, hiddenLayerSize)
W2 = np.random.randn(hiddenLayerSize, outputLayerSize)

# Apply the first weights to inputs to get hidden layer activity
Z2 = np.dot(X_norm, W1)
print("Z2 =")
print(Z2)

# Define our activation function
def sigmoid(z):
    #Apply sigmoid activation function to scalar, vector, or matrix
    return 1/(1+np.exp(-z))

# Apply the activation function to our activity levels
a2 = sigmoid(Z2)
print("a2 =")
print(a2)

# Apply the second weights to the hidden layer
Z3 = np.dot(a2, W2)
print("Z3 =")
print(Z3)

# Apply the activation function to produce prediction for yHat
yHat = sigmoid(Z3)

# Compare yhat to known y_norm
print("--------------")
print("How did we do?")
print("y_norm:")
print(y_norm)
print("yHat:")
print(yHat)

X_norm =
[[0.3 0.5]
 [0.5 0.1]
 [1.  0.2]]
y_norm =
[[0.75]
 [0.83]
 [0.93]]
Z2 =
[[-0.1506522   0.12206046 -0.43022619]
 [-0.40625587  0.30925163  0.03331028]
 [-0.81251175  0.61850326  0.06662057]]
a2 =
[[0.46240802 0.53047728 0.39407232]
 [0.39981023 0.57670258 0.5083268 ]
 [0.30735552 0.64987806 0.51664898]]
Z3 =
[[-1.29563265]
 [-1.48535053]
 [-1.42904345]]
--------------
How did we do?
y_norm:
[[0.75]
 [0.83]
 [0.93]]
yHat:
[[0.21490095]
 [0.18462061]
 [0.19324777]]


----
# 2. Work on semester projects

This is a chance to make some progress on your project with your group while the instructors are around to help. Make use of it!

Before you leave, answer the following questions:

1. Where are you at with your project?
    - What have you accomplished?
    - What do you still need to do?
2. What do you think your biggest obstacle will be in completing your assignment?
3. When is your group going to meet to continue working on or finish the project?

*Put your answers here!*
1. We decided on what ABM style we would do and what the general starting objects are
2. The complexity of all the moving parts of the project. 
3. ASAP, we want to figure out who is doing what

-----
### Congratulations, you're done!

Submit this notebook to D2L so that your instructor knows where you're at with your project!

&#169; Copyright 2018,  Michigan State University Board of Trustees